// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AddTorrentRequest adds torrent files, a magnet link, or an http(s) URL.
 */
export interface AddTorrentRequest {
    "metainfo": string[] | null;
    "url": string;
    "directory": string;
    "start": boolean;
}

/**
 * DownloadLocation is the folder new torrents use and the free space there.
 * FreeBytes is -1 when the daemon cannot report free space.
 */
export interface DownloadLocation {
    "path": string;
    "freeBytes": number;
}

/**
 * Peer is one connected peer on a torrent.
 */
export interface Peer {
    "encrypted": boolean;
    "rateToPeer": number;
    "rateToClient": number;
    "progress": number;
    "flagStr": string;
    "address": string;
    "clientName": string;
}

/**
 * Settings is the connection form. The password itself stays in the keychain.
 * Sort is the torrent list order restored when the app opens.
 */
export interface Settings {
    "url": string;
    "username": string;
    "hasPassword": boolean;
    "refreshSeconds": number;
    "sort": string;
}

/**
 * SettingsInput is a preferences save. An empty password keeps the saved one.
 */
export interface SettingsInput {
    "url": string;
    "username": string;
    "password": string;
    "clearPassword": boolean;
    "refreshSeconds": number;
}

/**
 * Torrent is the slice of a Transmission torrent shown in the list.
 */
export interface Torrent {
    "id": number;
    "name": string;
    "percentDone": number;
    "peersConnected": number;
    "rateDownload": number;
    "rateUpload": number;
    "uploadRatio": number;
    "status": string;
    "totalSize": number;
    "error": string;
}

/**
 * TorrentFile is one file inside a torrent.
 * Name is the path relative to the torrent, with "/" between folders.
 */
export interface TorrentFile {
    "name": string;
    "size": number;
    "have": number;
}

/**
 * TorrentInfo is the inspector snapshot for one torrent.
 */
export interface TorrentInfo {
    "id": number;
    "name": string;
    "status": string;
    "error": string;
    "percentDone": number;
    "have": number;
    "availability": number;
    "uploadedEver": number;
    "uploadRatio": number;
    "downloadedEver": number;
    "secondsActive": number;
    "eta": number;
    "activityDate": number;
    "totalSize": number;
    "pieceCount": number;
    "pieceSize": number;
    "downloadDir": string;
    "hashString": string;
    "addedDate": number;
    "magnetLink": string;
    "peers": Peer[] | null;
    "trackers": Tracker[] | null;
    "files": TorrentFile[] | null;
}

/**
 * Tracker is one announce URL and its latest announce and scrape result.
 * Tier is Transmission's zero-based tier.
 */
export interface Tracker {
    "announce": string;
    "tier": number;
    "hasAnnounced": boolean;
    "lastAnnounceTime": number;
    "lastAnnounceSucceeded": boolean;
    "lastAnnounceResult": string;
    "lastAnnouncePeerCount": number;
    "nextAnnounceTime": number;
    "hasScraped": boolean;
    "lastScrapeTime": number;
    "lastScrapeSucceeded": boolean;
    "lastScrapeResult": string;
    "seederCount": number;
    "leecherCount": number;
    "downloadCount": number;
}
