// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TransmissionService lists torrents on a remote Transmission daemon.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddTorrent sends one or more torrents to the daemon.
 */
export function AddTorrent(request: $models.AddTorrentRequest): $CancellablePromise<void> {
    return $Call.ByID(2807914026, request);
}

/**
 * DownloadLocation returns the default download directory when path is empty.
 */
export function DownloadLocation(path: string): $CancellablePromise<$models.DownloadLocation> {
    return $Call.ByID(395722186, path);
}

/**
 * Endpoint returns the RPC URL the service is using.
 */
export function Endpoint(): $CancellablePromise<string> {
    return $Call.ByID(2637037908);
}

/**
 * GetSettings returns the preferences form values.
 */
export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3276907602);
}

/**
 * GetTorrent returns the inspector fields for one torrent.
 */
export function GetTorrent(id: number): $CancellablePromise<$models.TorrentInfo> {
    return $Call.ByID(346218475, id);
}

/**
 * ListTorrents fetches every torrent from the configured daemon.
 */
export function ListTorrents(): $CancellablePromise<$models.Torrent[] | null> {
    return $Call.ByID(363672254);
}

/**
 * RemoveTorrent drops one torrent from the daemon.
 * deleteData also removes the downloaded files.
 */
export function RemoveTorrent(id: number, deleteData: boolean): $CancellablePromise<void> {
    return $Call.ByID(725758901, id, deleteData);
}

/**
 * SaveSettings stores the connection settings and reconnects.
 * The password is written to the keychain and is not saved in the JSON file.
 */
export function SaveSettings(input: $models.SettingsInput): $CancellablePromise<void> {
    return $Call.ByID(678405389, input);
}

/**
 * SetSort stores the torrent list sort so the next launch restores it.
 */
export function SetSort(sort: string): $CancellablePromise<void> {
    return $Call.ByID(1836082323, sort);
}

/**
 * StartTorrent resumes one torrent.
 */
export function StartTorrent(id: number): $CancellablePromise<void> {
    return $Call.ByID(624377315, id);
}

/**
 * StopTorrent pauses one torrent.
 */
export function StopTorrent(id: number): $CancellablePromise<void> {
    return $Call.ByID(3666365757, id);
}

/**
 * TakeOpenError returns a failed Open With add, then clears it.
 */
export function TakeOpenError(): $CancellablePromise<string> {
    return $Call.ByID(2330326664);
}
